# Generated by Django 4.2.3 on 2024-12-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_remove_participant_email_remove_prize_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prize',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
